name: Apply

on:
  workflow_dispatch:

# permissions:
#   id-token: write
#   contents: read
#   actions: read

jobs:

  apply:
    name: "Terraform"
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    
           
    # - name: Configure AWS credentials
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       role-to-assume: "${{ secrets.ROLE_ARN }}"
    #       role-session-name: github-actions-session
    #       aws-region: eu-west-2

      - name: Terraform validate
        run: |
          terraform init
          terraform fmt
          terraform validate

      - name: Linting
        uses: terraform-linters/setup-tflint@v4
      - run: |
          tflint --init
          tflint

      - name: Checkov Scan
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./terraform
          check: CKV_AWS_1,CKV_AWS_2,CKV_AWS_41
          soft_fail: true

      - name: Terraform Apply
        run: |
          terraform plan
          terraform apply -auto-approve