# docker build --platform linux/amd64 -t projects/eks-cluster .
# docker tag projects/url-shortner-repo:latest 354918400698.dkr.ecr.eu-west-2.amazonaws.com/projects/url-shortner-repo:latest# docker push 354918400698.dkr.ecr.eu-west-2.amazonaws.com/url-shortner-repo:latest
# docker push 354918400698.dkr.ecr.eu-west-2.amazonaws.com/projects/url-shortner-repo:latest
