
name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "yes" to confirm destruction'
        required: true

# permissions:
#   id-token: write

# defaults:
#   run:
#     working-directory: terraform/**
    
jobs:
  destroy:
   runs-on: ubuntu-latest    
   steps:
      - name: Checkout 
        uses: actions/checkout@v4
      
    #   - name: Configure AWS credentials 
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       role-to-assume: "${{ secrets.ROLE_ARN }}"
    #       aws-region: "${{ vars.REGION }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"

      - name: Terraform Destroy
        run: |
          cd ./terraform
          terraform init
          terraform destroy -auto-approve -input=false
